// web-svelte/src/lib/components/ui/Badge.svelte
<script lang="ts">
  import { cn } from '../../utils'

  const VARIANTS = {
    default: 'border-transparent bg-primary text-primary-foreground',
    secondary: 'border-transparent bg-secondary text-secondary-foreground',
    destructive: 'border-transparent bg-destructive text-white',
    outline: 'text-foreground',
  }

  let {
    class: className = '',
    variant = 'default',
    children,
  }: {
    class?: string
    variant?: keyof typeof VARIANTS
    children?: import('svelte').Snippet
  } = $props()
</script>

<div
  class={cn(
    'inline-flex items-center rounded-md border px-2 py-0.5 text-xs font-semibold transition-colors',
    VARIANTS[variant],
    className,
  )}
>
  {@render children?.()}
</div>

// web/src/components/ui/badge.tsx
import * as React from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'

const badgeVariants = cva(
  'inline-flex items-center rounded-md border px-2 py-0.5 text-xs font-semibold transition-colors',
  {
    variants: {
      variant: {
        default:     'border-transparent bg-primary text-primary-foreground',
        secondary:   'border-transparent bg-secondary text-secondary-foreground',
        destructive: 'border-transparent bg-destructive text-white',
        outline:     'text-foreground',
      },
    },
    defaultVariants: { variant: 'default' },
  }
)

export interface BadgeProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof badgeVariants> {}

function Badge({ className, variant, ...props }: BadgeProps) {
  return <div className={cn(badgeVariants({ variant }), className)} {...props} />
}

export { Badge, badgeVariants }
