// web-svelte/src/routes/reader/NovelReader.svelte
<script lang="ts">
  import { marked } from 'marked'

  let {
    content,
    fontSize,
    onRead,
    onProgress,
  }: {
    content: string
    fontSize: number
    onRead: () => void
    onProgress: (pct: number) => void
  } = $props()

  let didReport = false
  let scrollEl: HTMLDivElement | undefined = $state()
  const html = $derived(marked.parse(content) as string)

  $effect(() => {
    void content
    didReport = false
  })

  $effect(() => {
    const el = scrollEl
    if (!el) return
    function onScroll() {
      const el2 = el as HTMLDivElement
      const pct = el2.scrollHeight <= el2.clientHeight ? 1 : el2.scrollTop / (el2.scrollHeight - el2.clientHeight)
      onProgress(Math.min(1, pct))
      if (didReport) return
      if (el2.scrollTop + el2.clientHeight >= el2.scrollHeight - 100) {
        didReport = true
        onRead()
      }
    }
    el.addEventListener('scroll', onScroll, { passive: true })
    return () => el.removeEventListener('scroll', onScroll)
  })
</script>

<div bind:this={scrollEl} class="novel-scroll">
  <div class="mx-auto max-w-2xl px-6 py-10">
    <div class="novel-prose" style={`font-size: ${fontSize}px`}>
      {@html html}
    </div>
  </div>
</div>

// web/src/features/reader/components/NovelReader.tsx
import { useEffect, useRef } from 'react'
import { marked } from 'marked'

interface Props {
  content: string
  fontSize: number
  onRead: () => void
  onProgress: (pct: number) => void
}

export function NovelReader({ content, fontSize, onRead, onProgress }: Props) {
  const didReport = useRef(false)
  const scrollRef = useRef<HTMLDivElement>(null)
  const html = marked.parse(content) as string

  useEffect(() => {
    didReport.current = false
  }, [content])

  useEffect(() => {
    const el = scrollRef.current
    if (!el) return
    const onScroll = () => {
      const pct = el.scrollHeight <= el.clientHeight
        ? 1
        : el.scrollTop / (el.scrollHeight - el.clientHeight)
      onProgress(Math.min(1, pct))
      if (didReport.current) return
      if (el.scrollTop + el.clientHeight >= el.scrollHeight - 100) {
        didReport.current = true
        onRead()
      }
    }
    el.addEventListener('scroll', onScroll, { passive: true })
    return () => el.removeEventListener('scroll', onScroll)
  }, [onRead, onProgress])

  return (
    <div ref={scrollRef} className="novel-scroll">
      <div className="mx-auto max-w-2xl px-6 py-10">
        <div
          className="novel-prose"
          style={{ fontSize }}
          dangerouslySetInnerHTML={{ __html: html }}
        />
      </div>
    </div>
  )
}
