// web/src/features/queue/components/QueueRow.tsx
import { Clock, Loader2, Check, AlertCircle, X } from 'lucide-react'
import { type QueueItem } from '@/api'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

const STATUS: Record<string, { icon: React.ReactNode; badge: 'default' | 'secondary' | 'destructive' | 'outline' }> = {
  pending:     { icon: <Clock className="w-3.5 h-3.5" />,                badge: 'secondary'   },
  downloading: { icon: <Loader2 className="w-3.5 h-3.5 animate-spin" />, badge: 'default'     },
  done:        { icon: <Check className="w-3.5 h-3.5" />,                badge: 'outline'     },
  error:       { icon: <AlertCircle className="w-3.5 h-3.5" />,          badge: 'destructive' },
  cancelled:   { icon: <X className="w-3.5 h-3.5" />,                    badge: 'outline'     },
}

export function QueueRow({ item, onRemove }: { item: QueueItem; onRemove: () => void }) {
  const s = STATUS[item.status] ?? STATUS.pending

  return (
    <div className="flex items-center gap-3 py-3 border-b border-border last:border-0">
      <span className={cn(
        'shrink-0',
        item.status === 'error' ? 'text-destructive' :
        item.status === 'done' ? 'text-muted-foreground' : 'text-foreground',
      )}>
        {s.icon}
      </span>

      <div className="flex-1 min-w-0">
        <p className="text-sm font-medium truncate">{item.manga_title}</p>
        <p className="text-xs text-muted-foreground">Ch. {item.chapter_num}</p>
        {item.status === 'downloading' && item.pages_total > 0 && (
          <div className="mt-1.5 flex items-center gap-2">
            <div className="flex-1 h-1 bg-muted rounded-full overflow-hidden">
              <div
                className="h-full bg-primary transition-all duration-300"
                style={{ width: `${Math.round((item.pages_downloaded / item.pages_total) * 100)}%` }}
              />
            </div>
            <span className="text-xs text-muted-foreground tabular-nums shrink-0">
              {Math.round((item.pages_downloaded / item.pages_total) * 100)}%
            </span>
          </div>
        )}
        {item.error && (
          <p className="text-xs text-destructive mt-0.5 line-clamp-1">{item.error}</p>
        )}
      </div>

      <Badge variant={s.badge} className="shrink-0 capitalize">{item.status}</Badge>

      {item.status !== 'downloading' && (
        <Button variant="ghost" size="icon" className="shrink-0 h-7 w-7" onClick={onRemove}>
          <X className="w-3 h-3" />
        </Button>
      )}
    </div>
  )
}

// web-svelte/src/routes/queue/QueueRow.svelte
<script lang="ts">
  import { Clock, LoaderCircle, Check, CircleAlert, X } from '@lucide/svelte'
  import type { QueueItem } from '../../lib/api'
  import Badge from '../../lib/components/ui/Badge.svelte'
  import Button from '../../lib/components/ui/Button.svelte'
  import { cn } from '../../lib/utils'

  const STATUS: Record<string, { icon: typeof Clock; badge: 'default' | 'secondary' | 'destructive' | 'outline' }> = {
    pending:     { icon: Clock,        badge: 'secondary'   },
    downloading: { icon: LoaderCircle, badge: 'default'     },
    done:        { icon: Check,        badge: 'outline'     },
    error:       { icon: CircleAlert,  badge: 'destructive' },
    cancelled:   { icon: X,            badge: 'outline'     },
  }

  let { item, onRemove }: { item: QueueItem; onRemove: () => void } = $props()

  const s = $derived(STATUS[item.status] ?? STATUS.pending)
  const pct = $derived(item.pages_total > 0 ? Math.round((item.pages_downloaded / item.pages_total) * 100) : 0)
</script>

<div class="flex items-center gap-3 py-3 border-b border-border last:border-0">
  <span class={cn(
    'shrink-0',
    item.status === 'error' ? 'text-destructive' :
    item.status === 'done' ? 'text-muted-foreground' : 'text-foreground',
  )}>
    <s.icon class={cn('w-3.5 h-3.5', item.status === 'downloading' && 'animate-spin')} />
  </span>

  <div class="flex-1 min-w-0">
    <p class="text-sm font-medium truncate">{item.manga_title}</p>
    <p class="text-xs text-muted-foreground">Ch. {item.chapter_num}</p>
    {#if item.status === 'downloading' && item.pages_total > 0}
      <div class="mt-1.5 flex items-center gap-2">
        <div class="flex-1 h-1 bg-muted rounded-full overflow-hidden">
          <div class="h-full bg-primary transition-all duration-300" style={`width: ${pct}%`}></div>
        </div>
        <span class="text-xs text-muted-foreground tabular-nums shrink-0">{pct}%</span>
      </div>
    {/if}
    {#if item.error}
      <p class="text-xs text-destructive mt-0.5 line-clamp-1">{item.error}</p>
    {/if}
  </div>

  <Badge variant={s.badge} class="shrink-0 capitalize">{item.status}</Badge>

  {#if item.status !== 'downloading'}
    <Button variant="ghost" size="icon" class="shrink-0 h-7 w-7" onclick={onRemove}>
      <X class="w-3 h-3" />
    </Button>
  {/if}
</div>
