// web-svelte/src/App.svelte
<script lang="ts">
  import { router, matchPath } from './lib/router.svelte'
  import { ROUTES } from './lib/routes'
  import AppShell from './lib/AppShell.svelte'
  import Home from './routes/Home.svelte'
  import Library from './routes/Library.svelte'
  import Discover from './routes/Discover.svelte'
  import Queue from './routes/Queue.svelte'
  import Settings from './routes/Settings.svelte'
  import Login from './routes/Login.svelte'
  import Setup from './routes/Setup.svelte'
  import MangaDetail from './routes/MangaDetail.svelte'
  import Reader from './routes/Reader.svelte'

  const routeTable = [
    { pattern: ROUTES.home, component: Home, shell: true },
    { pattern: ROUTES.library, component: Library, shell: true },
    { pattern: '/title/:id', component: MangaDetail, shell: true },
    { pattern: ROUTES.discover, component: Discover, shell: true },
    { pattern: ROUTES.queue, component: Queue, shell: true },
    { pattern: ROUTES.settings, component: Settings, shell: true },
    { pattern: ROUTES.login, component: Login, shell: false },
    { pattern: ROUTES.setup, component: Setup, shell: false },
    { pattern: '/reader/:id', component: Reader, shell: false },
  ]

  function onUnauthorized() {
    router.navigate(ROUTES.login, { replace: true })
  }
  window.addEventListener('arrgh:unauthorized', onUnauthorized)

  const match = $derived.by(() => {
    for (const route of routeTable) {
      const params = matchPath(route.pattern, router.path)
      if (params) return { ...route, params }
    }
    return null
  })

  // Legacy /manga/:id -> /title/:id, unmatched paths -> home
  $effect(() => {
    if (match) return
    const legacy = matchPath('/manga/:id', router.path)
    router.navigate(legacy ? `/title/${legacy.id}` : ROUTES.home, { replace: true })
  })
</script>

{#if match}
  {#if match.shell}
    <AppShell>
      {#snippet children()}
        <match.component {...match.params} />
      {/snippet}
    </AppShell>
  {:else}
    <match.component {...match.params} />
  {/if}
{/if}

// web/src/App.tsx
import { useEffect, useState } from 'react'
import { Routes, Route, Navigate, useNavigate, useParams } from 'react-router-dom'
import AppLayout from './components/AppLayout'
import Home from './features/home'
import Library from './features/library'
import MangaDetail from './features/manga-detail'
import Reader from './features/reader'
import Settings from './features/settings'
import Discover from './features/discover'
import Queue from './features/queue'
import Login from './features/login'
import Setup from './features/setup'
import { api, getToken, clearToken } from './api'
import { ROUTES } from './lib/routes'

function MangaLegacyRedirect() {
  const { id } = useParams<{ id: string }>()
  return <Navigate to={`/title/${id}`} replace />
}

type AuthState = 'checking' | 'needs_setup' | 'needs_login' | 'authenticated'

function AuthGate({ children }: { children: React.ReactNode }) {
  const [state, setState] = useState<AuthState>('checking')
  const navigate = useNavigate()

  useEffect(() => {
    const token = getToken()
    if (!token) {
      api.authStatus()
        .then((s) => setState(s.needs_setup ? 'needs_setup' : 'needs_login'))
        .catch(() => setState('needs_setup'))
      return
    }

    api.me()
      .then(() => setState('authenticated'))
      .catch(() => {
        clearToken()
        setState('needs_login')
      })
  }, [])

  useEffect(() => {
    function onUnauthorized() {
      setState('needs_login')
    }
    window.addEventListener('arrgh:unauthorized', onUnauthorized)
    return () => window.removeEventListener('arrgh:unauthorized', onUnauthorized)
  }, [])

  useEffect(() => {
    if (state === 'needs_setup') navigate(ROUTES.setup, { replace: true })
    else if (state === 'needs_login') navigate(ROUTES.login, { replace: true })
  }, [state, navigate])

  if (state === 'checking') {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="w-6 h-6 rounded-full border-2 border-primary border-t-transparent animate-spin" />
      </div>
    )
  }

  if (state !== 'authenticated') return null

  return <>{children}</>
}

export default function App() {
  return (
    <Routes>
      {/* Public */}
      <Route path={ROUTES.login} element={<Login />} />
      <Route path={ROUTES.setup} element={<Setup />} />

      {/* Protected */}
      <Route element={
        <AuthGate>
          <AppLayout />
        </AuthGate>
      }>
        <Route path={ROUTES.home}     element={<Home />} />
        <Route path={ROUTES.library}  element={<Library />} />
        <Route path="/title/:id"      element={<MangaDetail />} />
        <Route path="/manga/:id"      element={<MangaLegacyRedirect />} />
        <Route path={ROUTES.settings} element={<Settings />} />
        <Route path={ROUTES.discover} element={<Discover />} />
        <Route path={ROUTES.queue}    element={<Queue />} />
      </Route>

      {/* Reader — protected but no AppLayout */}
      <Route path="/reader/:chapterId" element={
        <AuthGate>
          <Reader />
        </AuthGate>
      } />

      <Route path="*" element={<Navigate to={ROUTES.home} replace />} />
    </Routes>
  )
}
