// web/src/features/setup/index.tsx
import { cn } from '@/lib/utils'
import { useSetup } from './hooks/useSetup'
import { StepAccount } from './components/StepAccount'
import { StepSettings } from './components/StepSettings'

export default function Setup() {
  const h = useSetup()

  return (
    <div className="min-h-screen bg-background flex items-center justify-center p-4">
      <div className="w-full max-w-sm space-y-8">
        <div className="text-center space-y-2">
          <h1 className="text-4xl font-black tracking-tight text-primary">*ARRgh</h1>
          {h.step === 1 ? (
            <>
              <p className="text-sm font-semibold">Welcome — create your account</p>
              <p className="text-xs text-muted-foreground">One-time setup for your self-hosted library.</p>
            </>
          ) : (
            <>
              <p className="text-sm font-semibold">Configure your library</p>
              <p className="text-xs text-muted-foreground">These can be changed later in Settings.</p>
            </>
          )}
        </div>

        <div className="flex items-center justify-center gap-2">
          {([1, 2] as const).map((s) => (
            <div key={s} className={cn('w-2 h-2 rounded-full transition-colors', h.step >= s ? 'bg-primary' : 'bg-muted')} />
          ))}
        </div>

        {h.step === 1
          ? <StepAccount onDone={h.goToStep2} />
          : <StepSettings onDone={h.finish} />
        }
      </div>
    </div>
  )
}

// web-svelte/src/routes/Setup.svelte
<script lang="ts">
  import { cn } from '../lib/utils'
  import { SetupStore } from '../lib/setup.svelte'
  import StepAccount from './setup/StepAccount.svelte'
  import StepSettings from './setup/StepSettings.svelte'

  let _params: Record<string, string> = $props()

  const store = new SetupStore()
</script>

<div class="min-h-screen bg-background flex items-center justify-center p-4">
  <div class="w-full max-w-sm space-y-8">
    <div class="text-center space-y-2">
      <h1 class="text-4xl font-black tracking-tight text-primary">*ARRgh</h1>
      {#if store.step === 1}
        <p class="text-sm font-semibold">Welcome — create your account</p>
        <p class="text-xs text-muted-foreground">One-time setup for your self-hosted library.</p>
      {:else}
        <p class="text-sm font-semibold">Configure your library</p>
        <p class="text-xs text-muted-foreground">These can be changed later in Settings.</p>
      {/if}
    </div>

    <div class="flex items-center justify-center gap-2">
      {#each [1, 2] as s (s)}
        <div class={cn('w-2 h-2 rounded-full transition-colors', store.step >= s ? 'bg-primary' : 'bg-muted')}></div>
      {/each}
    </div>

    {#if store.step === 1}
      <StepAccount onDone={() => store.goToStep2()} />
    {:else}
      <StepSettings onDone={() => store.finish()} />
    {/if}
  </div>
</div>
